"""News / RSS collection.

Covers regular RSS feeds AND Google News *search* feeds (URLs generated by the wizard).
Key behaviours required by the spec:
  * date-range injection (after:/before:) with monthly/weekly chunking to beat the
    ~100-results-per-query cap;
  * comma-separated OR keyword filter;
  * strict relevance validation (headline match keeps; otherwise fetch body, strip
    related-articles/boilerplate BEFORE checking, drop if no term in real content,
    store fetched paragraphs as the item text);
  * first-paragraph fetch when a feed summary merely repeats the title;
  * best-effort Google News redirect resolution;
  * per-feed health check.

Regular RSS cannot reach back in time — only chunked Google News (and GDELT) can. This
limitation is documented in the export Methodology.
"""
from __future__ import annotations

import calendar
from datetime import date, datetime, timedelta
from typing import Any, Callable, Dict, List, Optional
from urllib.parse import parse_qs, quote_plus, urlparse, urlunparse

from scrapers import relevance
from scrapers.base import ScrapeResult, relevance_terms

CHANNEL = "news"


# --------------------------------------------------------------------------- #
# Pure helpers (unit-tested without network)
# --------------------------------------------------------------------------- #
def _as_date(d) -> date:
    if isinstance(d, datetime):
        return d.date()
    if isinstance(d, date):
        return d
    return datetime.strptime(str(d)[:10], "%Y-%m-%d").date()


def _first_of_next_month(d: date) -> date:
    if d.month == 12:
        return date(d.year + 1, 1, 1)
    return date(d.year, d.month + 1, 1)


def chunk_date_ranges(start, end, mode: str = "monthly") -> List[Dict[str, str]]:
    """Contiguous half-open [after, before) windows covering [start, end].

    Consecutive windows share a boundary (prev['before'] == next['after']) so there
    are no gaps and no overlaps. Used to inject after:/before: into Google News.
    """
    start_d = _as_date(start)
    end_d = _as_date(end)
    if end_d <= start_d:
        return [{"after": start_d.isoformat(), "before": end_d.isoformat()}] if end_d == start_d else []

    ranges: List[Dict[str, str]] = []
    cur = start_d
    while cur < end_d:
        if mode == "weekly":
            nxt = cur + timedelta(days=7)
        elif mode == "daily":
            nxt = cur + timedelta(days=1)
        elif mode == "none":
            nxt = end_d
        else:  # monthly (default)
            nxt = _first_of_next_month(cur)
        if nxt > end_d:
            nxt = end_d
        ranges.append({"after": cur.isoformat(), "before": nxt.isoformat()})
        cur = nxt
    return ranges


def matches_or_filter(text: str, keywords: List[str]) -> bool:
    """Comma-separated OR keyword filter: keep if ANY keyword is present."""
    if not keywords:
        return True
    hay = (text or "").lower()
    return any(kw.strip().lower() in hay for kw in keywords if kw.strip())


def parse_or_keywords(raw: str) -> List[str]:
    """Accept a comma-separated OR keyword string."""
    return [k.strip() for k in (raw or "").split(",") if k.strip()]


def parse_feed(xml_text: str) -> List[Dict[str, str]]:
    """Parse RSS/Atom into normalized entries via feedparser."""
    import feedparser

    parsed = feedparser.parse(xml_text)
    out: List[Dict[str, str]] = []
    for e in parsed.entries:
        published = ""
        if getattr(e, "published", None):
            published = e.published
        elif getattr(e, "updated", None):
            published = e.updated
        # Normalize published to ISO date if parseable.
        pub_iso = published
        if getattr(e, "published_parsed", None):
            try:
                pub_iso = datetime(*e.published_parsed[:6]).date().isoformat()
            except Exception:
                pub_iso = published
        out.append(
            {
                "title": getattr(e, "title", "") or "",
                "link": getattr(e, "link", "") or "",
                "summary": getattr(e, "summary", "") or getattr(e, "description", "") or "",
                "published": pub_iso,
                "source": (getattr(getattr(e, "source", None), "title", "") or ""),
                # The outlet's own homepage URL (e.g. https://www.nst.com.my). Reliable
                # geography signal even when the article link is an obfuscated GN redirect.
                "source_url": (getattr(getattr(e, "source", None), "href", "") or ""),
            }
        )
    return out


def inject_date_range(google_news_url: str, after: str, before: str) -> str:
    """Add after:/before: operators to a Google News search feed URL's q param."""
    parsed = urlparse(google_news_url)
    qs = parse_qs(parsed.query)
    q = qs.get("q", [""])[0]
    # Remove any pre-existing date operators, then append fresh ones.
    q = " ".join(tok for tok in q.split() if not tok.startswith(("after:", "before:")))
    q = f"{q} after:{after} before:{before}".strip()
    qs["q"] = [q]
    new_query = "&".join(
        f"{k}={quote_plus(v[0], safe=':')}" if k == "q" else f"{k}={v[0]}" for k, v in qs.items()
    )
    return urlunparse(parsed._replace(query=new_query))


def is_google_news_url(url: str) -> bool:
    return "news.google.com" in (url or "")


def decode_google_news_url(url: str) -> Optional[str]:
    """Best-effort recovery of the publisher URL encoded in a Google News RSS link.

    Google News article links look like .../rss/articles/CBMi<base64>… . The real
    publisher URL is often embedded (base64) in that token. This is inherently
    fragile (Google changes it), so it is strictly best-effort and never trusted
    blindly — callers fall back to redirect-following and honest failure.
    """
    import base64
    import re as _re

    m = _re.search(r"/(?:rss/)?articles/([A-Za-z0-9_\-]+)", url or "")
    if not m:
        return None
    token = m.group(1)
    try:
        raw = base64.urlsafe_b64decode(token + "=" * (-len(token) % 4))
    except Exception:
        return None
    text = raw.decode("latin-1", errors="ignore")
    found = _re.search(r"https?://[^\s\x00-\x1f\"'\\<>]+", text)
    if not found:
        return None
    cand = found.group(0)
    return None if "news.google" in cand else cand


def extract_publisher_link(html: str) -> Optional[str]:
    """Pull the outbound publisher link from a Google News interstitial page."""
    import re as _re

    from bs4 import BeautifulSoup

    mm = _re.search(r'url=(https?://[^"\'>\s]+)', html or "", _re.I)
    if mm and "google" not in mm.group(1):
        return mm.group(1)
    soup = BeautifulSoup(html or "", "html.parser")
    a = soup.find("a", href=True)
    if a and a["href"].startswith("http") and "google" not in a["href"]:
        return a["href"]
    return None


def resolve_and_fetch(link: str, fetch) -> tuple:
    """Return (resolved_url, html). For Google News links, resolve to the publisher
    page first (decode -> redirect -> interstitial parse); for normal links, one fetch.
    Returns (None, None) on failure so the caller falls back honestly."""
    if not is_google_news_url(link):
        r = fetch(link)
        if getattr(r, "status_code", 200) >= 400:
            return None, None
        return getattr(r, "url", link) or link, getattr(r, "text", "") or ""

    # Google News redirect link.
    pub = decode_google_news_url(link)
    if pub:
        try:
            r = fetch(pub)
            if getattr(r, "status_code", 200) < 400:
                return getattr(r, "url", pub) or pub, getattr(r, "text", "") or ""
        except Exception:
            pass
    try:
        r = fetch(link)
        final = getattr(r, "url", link) or link
        html = getattr(r, "text", "") or ""
        if not is_google_news_url(final):
            return final, html
        pl = extract_publisher_link(html)
        if pl:
            try:
                r2 = fetch(pl)
                if getattr(r2, "status_code", 200) < 400:
                    return getattr(r2, "url", pl) or pl, getattr(r2, "text", "") or ""
            except Exception:
                pass
        return final, html  # last resort — may still be the interstitial
    except Exception:
        return None, None


def market_signal(haystack: str, domain: str, market_terms: List[str], cctld: str) -> bool:
    """True if there's evidence the item is in-market. With no market config, always
    True (no filtering). Country name matches its demonym via substring."""
    if not market_terms and not cctld:
        return True
    hay = (haystack or "").lower()
    for t in market_terms:
        if t and t.lower() in hay:
            return True
    if cctld and domain and domain.lower().endswith(cctld.lower()):
        return True
    return False


def summary_echoes_title(title: str, summary: str) -> bool:
    """True when the feed summary is basically just the headline (no real content)."""
    from bs4 import BeautifulSoup

    text = BeautifulSoup(summary or "", "html.parser").get_text(" ", strip=True)
    t = (title or "").strip().lower()
    s = text.strip().lower()
    if not s:
        return True
    return s == t or (t and t in s and len(s) <= len(t) + 15)


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
def _default_fetch(url: str):
    from http_client import get_session

    return get_session().get(url, allow_redirects=True)


def collect(
    cfg: Dict[str, Any],
    params: Optional[Dict[str, Any]] = None,
    *,
    fetch_fn: Optional[Callable[[str], Any]] = None,
) -> ScrapeResult:
    """Collect news items across Google News search feeds + regular RSS feeds.

    params:
      start_date, end_date (ISO) — window for Google News chunking (regular RSS ignores).
      chunk — 'monthly' | 'weekly' | 'daily' | 'none'.
      or_keywords — comma-separated OR filter applied to title+summary.
      fetch_bodies — bool (default True): fetch article body for relevance/enrichment.
    """
    params = params or {}
    fetch = fetch_fn or _default_fetch
    result = ScrapeResult(CHANNEL)
    terms = relevance_terms(cfg)
    or_keywords = parse_or_keywords(params.get("or_keywords", ""))
    fetch_bodies = params.get("fetch_bodies", True)
    chunk_mode = params.get("chunk", cfg.get("collection_settings", {}).get("news_chunk", "monthly"))

    # Market gate — drops off-market items (e.g. Indian coverage in a Malaysia study).
    # Falls back to deriving terms/cctld from the market block, so existing projects
    # benefit without being re-created.
    market = cfg.get("market", {})
    country = market.get("country", "")
    market_only = params.get("market_only")
    if market_only is None:
        market_only = cfg.get("collection_settings", {}).get("market_filter", True)
    market_terms = params.get("market_terms") or market.get("market_terms") or (
        [country] if country else [])
    cctld = market.get("cctld") or (
        f".{market.get('country_code','').lower()}" if market.get("country_code") else "")
    mkt = {"only": bool(market_only), "terms": market_terms, "cctld": cctld}

    today = date.today()
    start_date = params.get("start_date") or (today - timedelta(days=90)).isoformat()
    end_date = params.get("end_date") or today.isoformat()

    plan = cfg.get("source_plan", {})
    seen_links: set = set()
    result.diagnostics["off_market_dropped"] = 0

    # 1) Google News search feeds (chunked over the date window).
    for feed in plan.get("google_news_feeds", []):
        base_url = feed.get("url")
        if not base_url:
            continue
        try:
            for window in chunk_date_ranges(start_date, end_date, chunk_mode):
                url = inject_date_range(base_url, window["after"], window["before"])
                _collect_feed(url, terms, or_keywords, fetch, fetch_bodies, result, seen_links,
                              is_google_news=True, feed_meta=feed, mkt=mkt)
        except Exception as exc:
            result.error(f"Google News feed failed ({feed.get('language')}/{feed.get('structure')}): {exc}")

    # 2) Bing News search feeds — a SECOND, independent index (catches sources Google
    # News's crawl missed). No date-range operator support, so this runs once per feed
    # rather than chunked; still fully market-filtered, relevance-validated, and
    # participates in the same dedup/clustering as everything else.
    if params.get("bing_news", True):
        for feed in plan.get("bing_news_feeds", []):
            base_url = feed.get("url")
            if not base_url:
                continue
            try:
                _collect_feed(base_url, terms, or_keywords, fetch, fetch_bodies, result, seen_links,
                              is_google_news=True, feed_meta=feed, mkt=mkt, engine="bing_news")
            except Exception as exc:
                result.error(f"Bing News feed failed ({feed.get('language')}/{feed.get('structure')}): {exc}")

    # 3) Regular RSS feeds (no time travel; current window only). These are already the
    # publisher's own feed, so market gating is skipped (the outlet IS the market signal).
    for rss_url in plan.get("rss_feeds", []):
        try:
            _collect_feed(rss_url, terms, or_keywords, fetch, fetch_bodies, result, seen_links,
                          is_google_news=False, feed_meta={"url": rss_url},
                          mkt={"only": False, "terms": [], "cctld": ""})
        except Exception as exc:
            result.error(f"RSS feed failed ({rss_url}): {exc}")

    if mkt["only"] and result.diagnostics["off_market_dropped"]:
        result.error(f"Market filter dropped {result.diagnostics['off_market_dropped']} off-market "
                     f"item(s) (no signal they relate to {country or 'the target market'}). "
                     f"Disable with market_only=false, or add city/region terms to market_terms.")

    return result


def _collect_feed(url, terms, or_keywords, fetch, fetch_bodies, result, seen_links,
                  *, is_google_news, feed_meta, mkt=None, engine=None):
    mkt = mkt or {"only": False, "terms": [], "cctld": ""}
    # is_google_news controls "query-scoped feed" behavior (semantic backstop instead of
    # hard-drop, always-fetch-body) — Bing News feeds are ALSO query-scoped and share
    # that behavior, so they pass is_google_news=True too. `engine` is the accurate,
    # separate provenance tag stored on each item so exports/audits can tell them apart.
    engine = engine or ("google_news" if is_google_news else "rss")
    resp = fetch(url)
    status = getattr(resp, "status_code", 200)
    health = {"url": url, "status": status, "entries": 0, "kept": 0}
    if status and status >= 400:
        health["reason"] = f"HTTP {status}"
        result.diagnostics.setdefault("feeds", []).append(health)
        result.error(f"Feed unhealthy: {url} -> HTTP {status}")
        return

    entries = parse_feed(getattr(resp, "text", "") or "")
    health["entries"] = len(entries)

    for entry in entries:
        link = entry.get("link", "")
        if link and link in seen_links:
            continue

        title = entry.get("title", "")
        summary = entry.get("summary", "")
        haystack = f"{title} {summary}"
        if not matches_or_filter(haystack, or_keywords):
            continue

        article_html = None
        resolved_link = link
        body_resolved = False
        # Fetch the real article body when we need it: for relevance (no headline match)
        # OR to enrich a summary that just echoes the title (the common Google News case).
        need_body = fetch_bodies and (
            not relevance.contains_any_term(title, terms)
            or summary_echoes_title(title, summary)
            or is_google_news
        )
        if need_body and link:
            try:
                rlink, rhtml = resolve_and_fetch(link, fetch)
                if rhtml is not None:
                    article_html = rhtml
                    resolved_link = rlink or link
                    # Body counts as resolved only if we actually left Google News.
                    body_resolved = not is_google_news_url(resolved_link)
            except Exception as exc:
                result.error(f"Article fetch failed ({link}): {exc}")

        verdict = relevance.validate_relevance(title, terms, article_html)
        if not verdict["relevant"]:
            # A failed keyword check means one of two different things, and they must
            # be treated differently:
            #   (a) the term appears ONLY in boilerplate (related-links/footer/nav) —
            #       CONFIRMED junk per the spec's core example; always hard-drop.
            #   (b) the term appears NOWHERE on the page at all — no keyword evidence
            #       either way; MIGHT be a paraphrased mention worth a semantic look.
            footer_only_junk = bool(article_html) and relevance.term_appears_anywhere(article_html, terms)
            if not is_google_news or footer_only_junk or not article_html:
                # Regular RSS feeds are an UNSCOPED full firehose (not built from a
                # keyword query) — no bound on volume without this gate, so it stays.
                # Confirmed-junk and no-body-to-check cases also always hard-drop.
                continue
            # Reached only for: Google News (keyword-scoped query) + we have the real
            # page + the term is absent from the ENTIRE page, not just stripped
            # boilerplate. Store it instead of dropping — Claude's brand_focus tag
            # during Analyze makes the final relevance call (analytics excludes
            # brand_focus="unrelated" from headline stats; this item is never counted
            # as confirmed-relevant until that happens).

        # Stored text = the article's real FIRST PARAGRAPHS (below the title), not the
        # headline-echoing feed summary. Falls back to summary only when the body could
        # not be resolved.
        from bs4 import BeautifulSoup
        from urllib.parse import urlparse

        summary_text = BeautifulSoup(summary or "", "html.parser").get_text(" ", strip=True)
        # Pick the richest REAL body text available. For direct RSS feeds the feed's own
        # <description> is usually the article's lead paragraph (not a title-echo), so a
        # substantive summary is a first-class source — this is what gives real first-
        # paragraph text where Google News (title-echo only) cannot.
        candidates = []
        if article_html:
            fp = relevance.first_paragraphs(article_html)
            if fp and len(fp) > 60:  # real <p> body; avoid nav/chrome from <p>-less pages
                candidates.append(fp)
        if summary_text and not summary_echoes_title(title, summary_text) and len(summary_text) > 40:
            candidates.append(summary_text)
        text = max(candidates, key=len) if candidates else (summary_text or verdict["text"] or "")

        # Market gate: keep only items with a signal they're in-market. The most
        # reliable signal is the OUTLET's own domain (e.g. nst.com.my), which the feed
        # gives us even when the article URL is an obfuscated Google News redirect.
        domain = urlparse(resolved_link).netloc
        outlet_url = entry.get("source_url", "")
        outlet_domain = urlparse(outlet_url).netloc if outlet_url else ""
        gate_domain = outlet_domain or domain
        gate_hay = f"{title} {text} {summary_text} {entry.get('source','')} {outlet_domain}"
        if mkt["only"] and not market_signal(gate_hay, gate_domain, mkt["terms"], mkt["cctld"]):
            result.diagnostics["off_market_dropped"] = result.diagnostics.get("off_market_dropped", 0) + 1
            continue

        if link:
            seen_links.add(link)
        result.add(
            {
                "title": title,
                "text": text,
                "link": resolved_link,
                "published": entry.get("published", ""),
                "extra": {
                    "feed_url": url,
                    "is_google_news": is_google_news,
                    "engine": engine,  # "google_news" | "bing_news" | "rss"
                    "matched_in": verdict["matched_in"],
                    "language": feed_meta.get("language"),
                    "outlet": entry.get("source", "") or outlet_domain or domain,
                    "outlet_url": outlet_url,
                    "body_resolved": body_resolved,
                    # False = kept via the semantic backstop (no literal keyword match;
                    # Claude's brand_focus tag decides relevance during Analyze).
                    "relevance_precheck": verdict["relevant"],
                },
            }
        )
        health["kept"] += 1

    result.diagnostics.setdefault("feeds", []).append(health)
